$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoplayTimeout:1500,
    autoplayHoverPause:true,
    autoplay:true,

    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})